SET search_path TO gfi;

CREATE TABLE IF NOT EXISTS e_github_metadata
(
    id          BIGSERIAL PRIMARY KEY,
    created     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    label       VARCHAR(255)             NOT NULL UNIQUE,
    issue_count INTEGER                  NOT NULL
);

INSERT INTO e_github_metadata (label, issue_count)
VALUES ('documentation',54054),
    ('good first issue',29366),
            ('help wanted',23539),
            ('hacktoberfest',3033),
            ('easy',1637),
            ('good-first-issue',1379),
            ('help-wanted',1073),
            ('up-for-grabs',154),
            ('doc',127),
            ('contribution',115),
            ('code quality',101),
            ('beginner',103),
            ('up for grabs',103),
            ('contribution welcome',87),
            ('beginner-friendly',74),
            ('E-easy',62),
            ('beginner friendly',45),
            ('low-hanging-fruit',45),
            ('first-timers-only',35),
            ('low hanging fruit',25),
            ('Low-Hanging Fruit',31),
            ('first-contribution',29),
            ('easy-fix',28),
            ('Easy hack',26),
            ('Good first issue!',25),
            ('easy task',21),
            ('good first bug',16),
            ('Good First Task',16),
            ('E-less-complex',12),
            ('Status: Up for grabs',11),
            ('status: ideal-for-contribution',9),
            ('starter-task',8),
            ('newbie-friendly',7),
            ('newbie',7),
            ('Portfolio Addition',5),
            ('Type: Good first issue',5),
            ('hint/good first issue',5),
            ('Great First Issue',5),
            ('bite-sized',5),
            ('level:starter',4),
            ('easy-pick',4),
            ('effort/easy',2),
            ('starter issue',2),
            ('good-first-bug',2),
            ('Junior Jobs',2),
            ('Newcomers',2),
            ('scope:small',1),
            ('please contribute',1),
            ('co.help-wanted',1),
            ('upforgrabs',1),
            ('difficulty::easy',1),
            ('flag: good-first-issue',1),
            ('first contribution',1),
            ('easy_to_fix',1)
ON CONFLICT (label) DO NOTHING ;

